### ISSUE TITLE
No background color for file selection

### ISSUE THREAD

**Issue by ivanlivn** [rcvd/obsidian_ia#1]
Loving the theme btw! I don't seem to see any background color when trying to select or link to a file. E.g., when linking to a new note, the autocomplete that pops up doesn't show which file I am hovering over or when using arrow keys so it's hard to select the right note. Or when using the cmd+O file switcher.

**Comment by rcvd** [comment]
Fixed in latest commit, I'm now using the highlight color. Thanks for the suggestion.
