### ISSUE TITLE
What version of Quattro is expected?

### ISSUE THREAD

**Issue by ryanpcmcquen** [rcvd/obsidian_ia#12]
Thank you for this awesome theme! Are we expected to install the 'Static' or 'Variable' version of iA Quattro?

**Comment by rcvd** [comment]
Both should work. Variable is the default, static the fallback.

**Comment by ryanpcmcquen** [comment]
Looks like Mono is also expected for some UI elements (when looking at the CSS). Might be nice to mention that on the README. 🙂
