### ISSUE TITLE
Heading size request

### ISSUE THREAD

**Issue by ozgurirmak** [rcvd/obsidian_ia#2]
Great theme, thanks for sharing. I have a suggestion regarding the headings:
It would be great if headings were **bigger than the body font size** for easier identification. Especially for the preview mode. Thanks

**Comment by rcvd** [comment]
I try to mimic iA Writers Quattro theme, but you can add this to the bottom of the css file:

```
/* Ensure headings are distinguishable by font size in preview mode */
.markdown-preview-view h1 {
	font-size: 24px;
}
.markdown-preview-view h2 {
	font-size: 20px;
}
.markdown-preview-view h3 {
	font-size: 18px;
}
```
